# https://hydra.cc/docs/configure_hydra/intro/



run:
  dir: ${paths.log_dir}/${task_name}/runs/${version}


job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${task_name}.log