# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/score"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: 'sqlite:///hms2.db'
  
    # name of the study to persist optimization results
    study_name: hms2

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 40

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1234
      n_startup_trials: 8 # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      model.optimizer.lr: interval(0.0005, 0.001)
      model.optimizer.weight_decay: interval(0.00001, 0.0001)
      data.batch_size: choice(24, 32, 48, 64)
      preprocess.low_f: choice(0.0, 0.1)
      model.sim_mse_alpha: interval(0.0, 0.5)
      data.train_dataset.max_weight: choice(10, 20)
      data.train_dataset.transforms.0.p: interval(0.0, 0.5)
      data.train_dataset.transforms.1.p: interval(0.0, 0.5)
      data.train_dataset.transforms.2.p: interval(0.0, 0.5)
      data.train_dataset.transforms.3.p: interval(0.0, 0.5)
      data.train_dataset.transforms.4.p: interval(0.0, 0.5)
      data.train_dataset.transforms.6.p: interval(0.0, 0.5)
      data.train_dataset.transforms.7.p: interval(0.0, 0.5)
      data.train_dataset.transforms.8.p: interval(0.0, 0.5)
      data.train_dataset.transforms.9.p: interval(0.0, 0.5)
      data.train_dataset.transforms.9.max_shift: interval(0.0, 1)
      data.train_dataset.transforms.4.max_noise: interval(0.0, 0.2)
