_target_: src.nn_models.litmodels.LitModel

optimizer:
  _target_: timm.optim.MADGRAD
  _partial_: true
  lr: 0.003
  weight_decay: 0.000

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  max_lr: 0.001
  pct_start: 0.1
  total_steps: 1250
  div_factor: 10
  final_div_factor: 100

scheduler_interval: "step"

net:
  _target_: src.nn_models.basemodels.ConvRNNModel
  in_channels: 20
  latent_channels: 32
  num_outputs: 6
  kernel_size: 5
  stride: 1
  padding: 0
  dropout: 0.2
  num_blocks: 2


# compile model for faster training with pytorch 2.0
compile: true